python3 extract_scene.py hotel.py Intro
python3 extract_scene.py hotel.py Wifi
python3 extract_scene.py hotel.py Reconnaissance
python3 extract_scene.py hotel.py Defining
python3 extract_scene.py hotel.py BruteForce
python3 extract_scene.py hotel.py ProgramStructure
python3 extract_scene.py hotel.py Database
python3 extract_scene.py hotel.py CreateTable
python3 extract_scene.py hotel.py Select
