#!/usr/bin/env bash
python3 extract_scene.py streamer_ai.py Intro
python3 extract_scene.py streamer_ai.py InputANN
python3 extract_scene.py streamer_ai.py NeuralNetwork
python3 extract_scene.py streamer_ai.py Sigmoid
python3 extract_scene.py streamer_ai.py Relu
python3 extract_scene.py streamer_ai.py LeakyRelu
python3 extract_scene.py streamer_ai.py SoftMax
python3 extract_scene.py streamer_ai.py LayerToLayer
python3 extract_scene.py streamer_ai.py BackProp
python3 extract_scene.py streamer_ai.py NeuroEvolution
python3 extract_scene.py streamer_ai.py TWEANN
python3 extract_scene.py streamer_ai.py Commentary
python3 extract_scene.py streamer_ai.py StreamLabs
python3 extract_scene.py streamer_ai.py API
python3 extract_scene.py streamer_ai.py SocketAPI
python3 extract_scene.py streamer_ai.py GTTS
python3 extract_scene.py streamer_ai.py CGame
python3 extract_scene.py streamer_ai.py ANNTitle
python3 extract_scene.py streamer_ai.py LayerTitle
python3 extract_scene.py streamer_ai.py TrainingTitle
python3 extract_scene.py streamer_ai.py OtherTitle
python3 extract_scene.py streamer_ai.py SocketTitle
